#! /bin/sh

sxhkd &
picom &
pgrep bspswallow || bspswallow &

$HOME/.config/polybar/launch.sh
bspc monitor -d I II III IV V VI

bspc config focused_border_color  "#d8dee9"
bspc config normal_border_color   "#434c5e"
bspc config presel_feedback_color "#434c5e"

bspc config border_width         4
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
setxkbmap -option grp:alt_shift_toggle us,ir
